### ISSUE TITLE
 undefined reference to `Mesh::InitUserMeshData(ParameterInput*) Error

### ISSUE THREAD

**Issue by raginryan99** [PrincetonUniversity/athena-public-version#52]
I'm currently trying to get Athena++ to run on my Windows 10 computer but I get a " undefined reference to `Mesh::InitUserMeshData(ParameterInput*)'" when I attempt to make the \bin directory. I'm unsure of how to fix this problem or what could be causing it. I currently have python 3.7.7 installed, cygwin installed and g++ (GCC) 9.3.0. Sorry if I forgot to specify something this is all new to me. Thank you for your help.

**Comment by tomidakn** [comment]
I assume the error occured when you tried to build the code. (The bin directory should be automatically created.)

We do not test Athena++ on Cygwin and we cannot tell if there is anything with your environment or not. However, I do not expect any fundamental difficulty. At least it works with g++ 9.3.0. 

The InitUserMeshData function is defined with \_\_attribute\_\_((weak)) in src/pgen/default.cpp. The weak attribute means that this default implementation (which does nothing) is used unless you define this function in your own problem generator. So, it is possible that your installation is broken and this file is missing.

**Comment by felker** [comment]
Please share every command you used to configure and compile Athena++.

**Comment by raginryan99** [comment]
From within the athena directory, I ran "python configure.py" and then "make clean" and finally "make". The error occurs once I run the "make" command.

**Comment by felker** [comment]
Here is a possibly useful discussion: https://sourceware.org/legacy-ml/cygwin/2010-04/msg00281.html

Not sure if weak symbols (which are not in the C++ standard) will work in a Cygwin environment. There are Athena++ users who work on Windows (including @tomidakn ?) but they might be using MinGW, WSL, or something else. 

If you are only going to work with one problem generator, you could remove the weak symbols specifically tailored to that problem.

**Comment by tomidakn** [comment]
Sorry but I do not use Athena++ on Windows.

**Comment by tomidakn** [comment]
I installed Cygwin and tested it. I could reproduce the error (after changing the compilation option to -std=gnu++11). As Kyle pointed out, it seems that weak symbols do not work on Cygwin (I tested Clang too but it did not work. I guess this is rather a linker configuration).

I think we cannot support Athena++ on Cygwin. I did not test it by myself, but I would suggest to try WSL2 (Windows Subsystem for Linux), or actually recommend to install Linux on a virtual machine. 

If you really really want to use Athena++ on Cygwin, you can remove the weak symbols from those functions causing "undefined reference" errors in src/pgen/default.cpp. However, I would not recommend this strongly.
